###

###
GET http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
###
DELETE  http://localhost:3003/api/blogs/60f96f4acacc270e7c501530 HTTP/1.1
Content-Type: application/json
###
PUT  http://localhost:3003/api/blogs/60f9683774d7a637905cba2e HTTP/1.1
Content-Type: application/json

{
"title":"ee2",
"author":"fadd",
"url":"www.com",
"likes":333
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmgiLCJuYW1lIjoiQ2hhbmciLCJpZCI6IjYxYTNhZGQ2NGUwMDJkNWZjYzUwNWRjZiIsImlhdCI6MTYzODExNjg0Mn0.3C9kGLIAqAqVKeQ994GZ56NFvV7-sMcKpmCbMwDA7ck

{
"title":"new9",
"author":"fadd",
"url":"www.com",
"likes":33
}

### USER
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username":"minh",
  "password":"jakenguyen",
  "name":"minh"
}
###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username":"minh",
  "password":"ddsads",
  "name":"dasd"
}
###
GET http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3003/api/users/login HTTP/1.1
Content-Type: application/json

{
  "username":"minh",
  "password":"ddsads",
  "name":"dsd"
}

# {
#   "username":"dd",
#   "password":"cc1"
# }